# docker-compose.yml
version: '3.9'

services:
  db:
    image: postgres:15
    container_name: lokomotiv_postgres
    restart: always
    environment:
      POSTGRES_DB: lokomotiv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"   
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lokomotiv_net

  web:
    # ← твой Django
    build: .
    image: nurik345/lokomotivticket:latest
    container_name: lokomotiv_django
    restart: always
    env_file: .env
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lokomotiv_net

  frontend:    # ← будет тянуться из Docker Hub при деплое бэкенда
    image: nurik345/lokomotivticket-frontend:latest  # закомментируй эту строку
    container_name: lokomotiv_frontend
    restart: always
    expose:
      - "80"
    networks:
      - lokomotiv_net

  nginx:
    image: nginx:alpine
    container_name: lokomotiv_nginx
    restart: always
    ports:
      - "80:80"          # теперь весь сайт на порту 80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - web
      - frontend
    networks:
      - lokomotiv_net

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  lokomotiv_net:
    driver: bridge