services:
  web:
    image: nurik345/lokomotivticket:latest
    container_name: lokomotiv_django
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=lokomotivTicket.settings.prod
    ports:
      - "8080:8000"
    depends_on:
      - db
    networks:
      - lokomotiv_net
    volumes:
      - static_volume:/app/staticfiles
      - ./static:/app/static  # Добавьте это для разработки
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate --noinput &&
             gunicorn lokomotivTicket.wsgi:application --bind 0.0.0.0:8000 --workers 3"
