name: Build and Deploy Backend + Full Stack

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nurik345
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nurik345/lokomotivticket:latest

      - name: Deploy everything to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 10.15.15.29
          username: megaton
          password: ${{ secrets.SERVER_PASS }}
          script: |
            |
            cd /home/loginServer/lokomotiv
            
            # Тянем новый бэкенд-образ + фронтенд (если обновился)
            docker compose pull web frontend nginx
            
            # Перезапускаем всё красиво
            docker compose up -d --force-recreate --remove-orphans
            
            sleep 10
            
            # Миграции и статика
            docker compose exec -T web python manage.py migrate --noinput
            docker compose exec -T web python manage.py collectstatic --noinput
            
            echo "Deploy completed: http://10.15.15.29"